os: osx
language: rust
cache: cargo
branches:
  only:
    - master
before_install:
  - rustup component add clippy rustfmt
script:
  - cargo test
  - cargo clippy --all-targets -- -D warnings
  - cargo fmt -- --check
