[package]
name = "urdr"
version = "0.1.0"
authors = ["Benjamin Duffield <bduffield@palantir.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
core-graphics = "0.19.0"
core-foundation = "0.7.0"
